### ISSUE TITLE
Many errors tryiong to compile MidiDCO in Arduino IDE

### ISSUE THREAD

**Issue by Tim-Deefield** [jeremymlong/MidiDCO#1]
Hi Jeremy,  I'm having many errors trying to compile the MidiDCO using Arduino1.8.19.  I started with the 1.8.15 IDE and it complained about the missing the LinkedList so I installed the latest LinkedList.  Then it complained about the #include<iostream>.  I upgraded to the 1.8.19 IDE thinking that might help but I am still having a multitude of problems too many to list but some of them are TCCR4B, PWM4B, Midi.read, TCCR4A.  Am I missing a library or using the wrong version IDE?  Some of the Google hits mentioned using LinkedList with C++ only?  I am trying to compile it for an Arduino Pro Micro as mentioned in the schematic.

Thanks for any help with this,
-Tim Heffield

**Comment by Tim-Deefield** [comment]
The comment should have said #include <iostream>,  the iostream got lost somehow.
-Tim

**Comment by jeremymlong** [comment]
@Tim-Deefield Yep, it wasn't building for me either.  Something must have changed in that LinkedList library. I switched it to a different library called simply [List](https://www.arduino.cc/reference/en/libraries/list/). I tested with version 2.1.0. You also need the [MIDI library](https://github.com/FortySevenEffects/arduino_midi_library). I tested this with version 5.0.2. I targeted 'Arduino Micro' and it built okay for me.  Give the updated code a try and let me know how it goes for you.

**Comment by Tim-Deefield** [comment]
Hi Jeremy,

 

Yes that fixed it!  Thank you so much for looking into this and for the reply.  I am going out of town in the morning so I won’t be able to test the hardware till next week.  I really like the way you are using PWM to create the DCO control voltage, it’s a nice all-in-one solution…can’t wait to try it.

 

Regards,

 

-Tim

**Comment by jeremymlong** [comment]
Glad to hear it's working for you. Let me know how the hardware portion goes.
